#ifndef MEETING_H
#define MEETING_H
void ChangeStartMeetingFlag(void);
void MeetingCarControl(void);
void ChangeEndMeetingFlag(void);
void MeetingCtrlFun(void);
void MeetingCtrlFun_1(void);
void MeetingCtrlFun_2(void);
#endif //!MEETING_H